### ISSUE TITLE
Bug loading JSON file

### ISSUE THREAD

**Issue by fernaper** [fernaper/opencv-draw-tools#57]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cv2_tools/Storage.py", line 40, in json_unzip
    compressed_dict = json.loads(compressed_dict)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "send_test.py", line 145, in <module>
    load_video(sys.argv[2])
  File "send_test.py", line 125, in load_video
    storage_cv2 = StorageCV2(path='salida.json')
  File "/usr/local/lib/python3.5/dist-packages/cv2_tools/Storage.py", line 120, in __init__
    self.load_from_file(path)
  File "/usr/local/lib/python3.5/dist-packages/cv2_tools/Storage.py", line 201, in load_from_file
    self.complete_structure = json_unzip(json.load(json_file))
  File "/usr/local/lib/python3.5/dist-packages/cv2_tools/Storage.py", line 42, in json_unzip
    raise RuntimeError("Could interpret the unzipped contents")
RuntimeError: Could interpret the unzipped contents

**Comment by fernaper** [comment]
I can't reproduce the error.
Right now I will close this issue, but if anyone found it another time, we will reopen it.
Next time we need more information, at least: `cv2_tools.__version__` and `JSON` meta info.
